[METADATA]
modified = 2019-12-29T23:07:00.000Z

[[ACCOUNTS]]
address = "rNixerUVPwrhxGDt4UooDu6FJ7zuofvjCF"
network = "main"
desc = "nixerFFM"

[[ACCOUNTS]]
address = "r9N4v3cWxfh4x6yUNjxNy3DbWUgbzMBLdk"
network = "main"
desc = "nixerFFM"

[[PRINCIPALS]]
name = "nixerFFM"
email = "xrptipbotstats@gmail.com"
twitter = "@nixerFFM"
