[METADATA]
modified = 2020-04-01T11:40:00.000Z

[[ACCOUNTS]]
address = "r9N4v3cWxfh4x6yUNjxNy3DbWUgbzMBLdk"
network = "main"
desc = "nixerFFM"

[[PRINCIPALS]]
name = "XRPTipBotStats"
email = "xrptipbotstats@gmail.com"
twitter = "@XRPTipBotStats"
